import type { VisibilityState } from "@tanstack/react-table"

/** Default Equipments table column visibility before user preferences are applied. */
export const DEFAULT_COLUMN_VISIBILITY: VisibilityState = {
  id: false,
  ma_thiet_bi: true,
  ten_thiet_bi: true,
  model: false,
  serial: true,
  cau_hinh_thiet_bi: false,
  phu_kien_kem_theo: false,
  hang_san_xuat: false,
  noi_san_xuat: false,
  nam_san_xuat: false,
  ngay_nhap: false,
  ngay_dua_vao_su_dung: false,
  nguon_kinh_phi: false,
  gia_goc: false,
  nam_tinh_hao_mon: false,
  ty_le_hao_mon: false,
  han_bao_hanh: false,
  vi_tri_lap_dat: false,
  nguoi_dang_truc_tiep_quan_ly: true,
  khoa_phong_quan_ly: true,
  tinh_trang_hien_tai: true,
  ngay_ngung_su_dung: false,
  ghi_chu: false,
  chu_ky_bt_dinh_ky: false,
  ngay_bt_tiep_theo: false,
  chu_ky_hc_dinh_ky: false,
  ngay_hc_tiep_theo: false,
  chu_ky_kd_dinh_ky: false,
  ngay_kd_tiep_theo: false,
  phan_loai_theo_nd98: true,
  so_luu_hanh: true,
}
