// Whitelist RPCs we allow through the proxy.
export const ALLOWED_FUNCTIONS = new Set<string>([
  'equipment_list',
  'equipment_get',
  'equipment_get_by_code',
  'equipment_create',
  'equipment_update',
  'equipment_delete',
  'equipment_restore',
  'equipment_bulk_delete',
  'equipment_count',
  'equipment_count_enhanced',
  'equipment_attention_list',
  'equipment_attention_list_paginated',
  'equipment_attachments_list',
  'equipment_attachment_create',
  'equipment_attachment_delete',
  'equipment_history_list',
  'equipment_list_enhanced',
  'equipment_list_for_reports',
  'equipment_aggregates_for_reports',
  'departments_list',
  'departments_list_for_tenant',
  'departments_list_for_facilities',
  'equipment_users_list_for_tenant',
  'equipment_locations_list_for_tenant',
  'equipment_classifications_list_for_tenant',
  'equipment_statuses_list_for_tenant',
  'equipment_funding_sources_list_for_tenant',
  'equipment_filter_buckets',
  'equipment_bulk_import',
  // Repairs
  'repair_request_list',
  'repair_request_get',
  'repair_request_create',
  'repair_request_update',
  'repair_request_approve',
  'repair_request_complete',
  'repair_request_delete',
  'get_repair_request_facilities',
  'repair_request_status_counts',
  'repair_request_change_history_list',
  'repair_request_active_for_equipment',
  // Transfers
  'transfer_request_list',
  'transfer_request_page_data',
  'transfer_request_list_enhanced',
  'transfer_request_get',
  'transfer_request_create',
  'transfer_request_update',
  'transfer_request_update_status',
  'transfer_request_delete',
  'transfer_request_complete',
  'transfer_change_history_list',
  'transfer_request_external_pending_returns',
  'get_transfer_request_facilities',
  'get_equipment_location_suggestions',
  // Transfers - Data Grid
  'transfer_request_counts',
  // Maintenance
  'maintenance_plan_list',
  'maintenance_plan_get',
  'maintenance_plan_create',
  'maintenance_plan_update',
  'maintenance_plan_delete',
  'maintenance_plan_approve',
  'maintenance_plan_reject',
  'maintenance_tasks_list',
  'maintenance_tasks_list_with_equipment',
  'maintenance_tasks_bulk_insert',
  'maintenance_task_update',
  'maintenance_task_complete',
  'maintenance_tasks_delete',
  'maintenance_stats_enhanced',
  'maintenance_stats_for_reports',
  'get_maintenance_report_data',
  'maintenance_plan_status_counts',
  'dashboard_kpi_summary',
  // AI Assistant (read-only)
  'ai_equipment_lookup',
  'ai_maintenance_plan_lookup',
  'ai_maintenance_summary',
  'ai_repair_summary',
  'ai_usage_summary',
  'ai_attachment_metadata',
  'ai_device_quota_lookup',
  'ai_quota_compliance_summary',
  'ai_category_suggestion',
  'ai_department_list',
  'assistant_query_database_audit_log',
  // Tenants + Users
  'tenant_list',
  'get_facilities_with_equipment_count',
  'get_accessible_facilities',
  'user_create',
  'user_membership_add',
  'user_membership_remove',
  'user_set_current_don_vi',
  // Don vi (global-only management)
  'don_vi_list',
  'don_vi_get',
  'don_vi_create',
  'don_vi_update',
  'don_vi_set_active',
  'don_vi_user_hierarchy',
  // Usage Analytics (Reports)
  'usage_analytics_overview',
  'usage_analytics_daily',
  // Usage log management
  'usage_log_list',
  'usage_session_start',
  'usage_session_end',
  'usage_log_delete',
  // Reports: status distribution
  'equipment_status_distribution',
  // Audit logs (global users only)
  'audit_logs_list',
  'audit_logs_list_v2',
  'audit_logs_stats',
  'audit_logs_recent_summary',
  // Dashboard KPIs (tenant-filtered)
  'dashboard_repair_request_stats',
  'dashboard_maintenance_plan_stats',
  'dashboard_maintenance_count',
  'dashboard_equipment_total',
  'maintenance_calendar_events',
  'dashboard_recent_activities',
  // Debug
  'debug_claims',
  'test_jwt_claims',
  'don_vi_branding_get',
  // Header notifications
  'header_notifications_summary',
  // Device Quota Management (Dinh muc thiet bi)
  // Decisions
  'dinh_muc_quyet_dinh_list',
  'dinh_muc_quyet_dinh_get',
  'dinh_muc_quyet_dinh_create',
  'dinh_muc_quyet_dinh_update',
  'dinh_muc_quyet_dinh_activate',
  'dinh_muc_quyet_dinh_delete',
  // Categories
  'dinh_muc_nhom_list',
  'dinh_muc_nhom_list_paginated',
  'dinh_muc_nhom_get',
  'dinh_muc_nhom_upsert',
  'dinh_muc_nhom_delete',
  'dinh_muc_nhom_bulk_import',
  'dinh_muc_unified_import',
  // Equipment Mapping
  'dinh_muc_thiet_bi_link',
  'dinh_muc_thiet_bi_unlink',
  'dinh_muc_thiet_bi_unassigned',
  'dinh_muc_thiet_bi_unassigned_filter_options',
  'dinh_muc_thiet_bi_by_nhom',
  'dinh_muc_thiet_bi_by_ids',
  // Line Items
  'dinh_muc_chi_tiet_list',
  'dinh_muc_chi_tiet_upsert',
  'dinh_muc_chi_tiet_delete',
  'dinh_muc_chi_tiet_bulk_import',
  // Compliance
  'dinh_muc_compliance_summary',
  'dinh_muc_compliance_detail',
  // Suggested Mapping (read-path)
  'hybrid_search_category_batch',
  'dinh_muc_thiet_bi_unassigned_names',
  // Suggested Mapping (write-path)
  'dinh_muc_thiet_bi_link_batch',
])
