export type AiReadonlyViewName =
  | 'equipment_search'
  | 'maintenance_facts'
  | 'repair_facts'
  | 'usage_facts'
  | 'quota_facts'

export type AiReadonlySchema = Record<AiReadonlyViewName, readonly string[]>

export const AI_READONLY_SCHEMA: AiReadonlySchema = {
  equipment_search: [
    'equipment_id',
    'ma_thiet_bi',
    'ten_thiet_bi',
    'model',
    'serial',
    'hang_san_xuat',
    'noi_san_xuat',
    'nam_san_xuat',
    'so_luu_hanh',
    'nguon_nhap',
    'nguon_kinh_phi',
    'gia_goc',
    'nam_tinh_hao_mon',
    'ty_le_hao_mon',
    'han_bao_hanh',
    'phan_loai_theo_nd98',
    'nhom_thiet_bi_id',
    'tinh_trang_hien_tai',
    'khoa_phong_quan_ly',
    'nguoi_dang_truc_tiep_quan_ly',
    'vi_tri_lap_dat',
    'chu_ky_bt_dinh_ky',
    'ngay_bt_tiep_theo',
    'chu_ky_hc_dinh_ky',
    'ngay_hc_tiep_theo',
    'chu_ky_kd_dinh_ky',
    'ngay_kd_tiep_theo',
    'ngay_nhap_raw',
    'ngay_nhap_date',
    'ngay_nhap_year',
    'ngay_nhap_month',
    'ngay_nhap_quarter',
    'ngay_dua_vao_su_dung_raw',
    'ngay_dua_vao_su_dung_date',
    'ngay_dua_vao_su_dung_year',
    'ngay_dua_vao_su_dung_month',
    'ngay_dua_vao_su_dung_quarter',
    'ngay_ngung_su_dung_raw',
    'ngay_ngung_su_dung_date',
    'ngay_ngung_su_dung_year',
    'ngay_ngung_su_dung_month',
    'ngay_ngung_su_dung_quarter',
    'facility_id',
    'facility_code',
    'facility_name',
    'created_at',
  ],
  maintenance_facts: [
    'maintenance_task_id',
    'maintenance_plan_id',
    'equipment_id',
    'loai_cong_viec',
    'don_vi_thuc_hien',
    'diem_hieu_chuan',
    'task_notes',
    'ten_ke_hoach',
    'plan_year',
    'plan_status',
    'ngay_phe_duyet',
    'plan_facility_id',
    'ma_thiet_bi',
    'ten_thiet_bi',
    'model',
    'khoa_phong_quan_ly',
    'tinh_trang_hien_tai',
    'facility_id',
  ],
  repair_facts: [
    'repair_request_id',
    'equipment_id',
    'repair_status',
    'mo_ta_su_co',
    'hang_muc_sua_chua',
    'ngay_yeu_cau',
    'ngay_duyet',
    'ngay_hoan_thanh',
    'don_vi_thuc_hien',
    'ten_don_vi_thue',
    'chi_phi_sua_chua',
    'ma_thiet_bi',
    'ten_thiet_bi',
    'model',
    'khoa_phong_quan_ly',
    'facility_id',
    'facility_name',
  ],
  usage_facts: [
    'usage_log_id',
    'equipment_id',
    'thoi_gian_bat_dau',
    'thoi_gian_ket_thuc',
    'trang_thai',
    'tinh_trang_thiet_bi',
    'tinh_trang_ban_dau',
    'tinh_trang_ket_thuc',
    'ghi_chu',
    'duration_hours',
    'ma_thiet_bi',
    'ten_thiet_bi',
    'model',
    'khoa_phong_quan_ly',
    'facility_id',
  ],
  quota_facts: [
    'equipment_id',
    'ma_thiet_bi',
    'ten_thiet_bi',
    'model',
    'category_id',
    'category_code',
    'category_name',
    'facility_id',
    'facility_name',
    'decision_id',
    'so_quyet_dinh',
    'decision_status',
    'ngay_hieu_luc',
    'so_luong_toi_thieu',
    'so_luong_toi_da',
    'category_device_count',
    'quota_status',
    'remaining_quota',
  ],
}

export const AI_READONLY_VIEW_NAMES = Object.keys(
  AI_READONLY_SCHEMA,
) as AiReadonlyViewName[]

export const AI_READONLY_FORBIDDEN_REFERENCES = [
  'thiet_bi',
  'khoa_phong',
  'public.*',
  'auth.*',
  'pg_catalog.*',
  'set_config',
] as const

function formatSchemaSurface(): string {
  return AI_READONLY_VIEW_NAMES.map(
    viewName =>
      `ai_readonly.${viewName}(${AI_READONLY_SCHEMA[viewName].join(', ')})`,
  ).join('; ')
}

export const QUERY_DATABASE_TOOL_DESCRIPTION = [
  'Run exactly one read-only SQL SELECT on the ai_readonly semantic layer.',
  'Scope is already injected for one facility, so do not call set_config and do not assume cross-facility access.',
  `Allowed relations: ${formatSchemaSurface()}.`,
  'Department/khoa is the text column khoa_phong_quan_ly on these views; there is no separate khoa_phong table in ai_readonly.',
  'Common equipment reporting dimensions include khoa_phong_quan_ly, nguoi_dang_truc_tiep_quan_ly, vi_tri_lap_dat, phan_loai_theo_nd98, hang_san_xuat, noi_san_xuat, nguon_nhap, nguon_kinh_phi, nam_san_xuat, and gia_goc.',
  'For equipment date reporting, prefer the normalized buckets ngay_nhap_date/year/month/quarter, ngay_dua_vao_su_dung_date/year/month/quarter, and ngay_ngung_su_dung_date/year/month/quarter instead of parsing raw text inside SQL.',
  `Never use raw relations or schemas: ${AI_READONLY_FORBIDDEN_REFERENCES.join(', ')}.`,
  'Example 1: SELECT khoa_phong_quan_ly, COUNT(*) AS so_luong FROM ai_readonly.equipment_search GROUP BY khoa_phong_quan_ly ORDER BY so_luong DESC;',
  'Example 2: SELECT nguoi_dang_truc_tiep_quan_ly, COUNT(*) AS so_luong FROM ai_readonly.equipment_search GROUP BY nguoi_dang_truc_tiep_quan_ly ORDER BY so_luong DESC;',
  'Example 3: SELECT ngay_dua_vao_su_dung_year, COUNT(*) AS so_luong FROM ai_readonly.equipment_search GROUP BY ngay_dua_vao_su_dung_year ORDER BY ngay_dua_vao_su_dung_year;',
].join(' ')

export const QUERY_DATABASE_PROMPT_POINTER = [
  `Khi dùng \`query_database\`: chỉ viết đúng một câu \`SELECT\` trên các view ${AI_READONLY_VIEW_NAMES.join(', ')}.`,
  'Khoa/phòng nằm ở cột `khoa_phong_quan_ly`.',
  'Các chiều thống kê thiết bị phổ biến đã được công bố trong `equipment_search`, bao gồm `nguoi_dang_truc_tiep_quan_ly`, `vi_tri_lap_dat`, `phan_loai_theo_nd98`, `hang_san_xuat`, `noi_san_xuat`, `nguon_nhap`, `nguon_kinh_phi`, `nam_san_xuat`, `gia_goc`.',
  'Với câu hỏi theo ngày/tháng/quý/năm, ưu tiên dùng các cột chuẩn hóa như `ngay_nhap_date`, `ngay_nhap_year`, `ngay_nhap_month`, `ngay_nhap_quarter`, `ngay_dua_vao_su_dung_date`, `ngay_dua_vao_su_dung_year`, `ngay_dua_vao_su_dung_month`, `ngay_dua_vao_su_dung_quarter`, `ngay_ngung_su_dung_date`, `ngay_ngung_su_dung_year`, `ngay_ngung_su_dung_month`, `ngay_ngung_su_dung_quarter`.',
  `KHÔNG dùng raw schema/tên như ${AI_READONLY_FORBIDDEN_REFERENCES.join(', ')}.`,
].join(' ')
