-- Issue #544: credentials login attempt throttling.
-- Scope:
--   - add bounded throttle state table
--   - add service-role-only throttle RPCs
--   - allow rate_limited auth audit reason for forensic logging

BEGIN;

CREATE TABLE IF NOT EXISTS public.auth_login_attempt_throttle (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket_type text NOT NULL,
  username_hash text NULL,
  ip_address inet NOT NULL,
  failed_count integer NOT NULL DEFAULT 0,
  window_started_at timestamptz NOT NULL DEFAULT now(),
  last_failed_at timestamptz NULL,
  blocked_until timestamptz NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT auth_login_attempt_throttle_bucket_type_check CHECK (
    bucket_type = ANY (ARRAY['username_ip', 'ip']::text[])
  ),
  CONSTRAINT auth_login_attempt_throttle_failed_count_check CHECK (failed_count >= 0),
  CONSTRAINT auth_login_attempt_throttle_bucket_shape_check CHECK (
    (bucket_type = 'username_ip' AND username_hash IS NOT NULL)
    OR (bucket_type = 'ip' AND username_hash IS NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_login_throttle_username_ip_unique
  ON public.auth_login_attempt_throttle (username_hash, ip_address)
  WHERE bucket_type = 'username_ip';

CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_login_throttle_ip_unique
  ON public.auth_login_attempt_throttle (ip_address)
  WHERE bucket_type = 'ip';

CREATE INDEX IF NOT EXISTS idx_auth_login_throttle_updated_at
  ON public.auth_login_attempt_throttle (updated_at);

REVOKE ALL ON TABLE public.auth_login_attempt_throttle FROM PUBLIC;
REVOKE ALL ON TABLE public.auth_login_attempt_throttle FROM anon;
REVOKE ALL ON TABLE public.auth_login_attempt_throttle FROM authenticated;

CREATE OR REPLACE FUNCTION public._auth_login_throttle_username_hash(p_username text)
RETURNS text
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT encode(extensions.digest(lower(btrim(p_username)), 'sha256'), 'hex')
$$;

CREATE OR REPLACE FUNCTION public._auth_login_throttle_record_bucket(
  p_bucket_type text,
  p_username_hash text,
  p_ip_address inet,
  p_threshold integer,
  p_window interval,
  p_block_duration interval
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_now timestamptz := now();
  v_row public.auth_login_attempt_throttle%ROWTYPE;
  v_reset_window boolean;
  v_failed_count integer;
BEGIN
  IF p_ip_address IS NULL
     OR p_threshold <= 0
     OR p_bucket_type NOT IN ('username_ip', 'ip')
     OR (p_bucket_type = 'username_ip' AND p_username_hash IS NULL)
     OR (p_bucket_type = 'ip' AND p_username_hash IS NOT NULL) THEN
    RETURN TRUE;
  END IF;

  LOOP
    SELECT *
    INTO v_row
    FROM public.auth_login_attempt_throttle
    WHERE bucket_type = p_bucket_type
      AND ip_address = p_ip_address
      AND (
        (p_bucket_type = 'ip' AND username_hash IS NULL)
        OR (p_bucket_type = 'username_ip' AND username_hash = p_username_hash)
      )
    FOR UPDATE;

    IF NOT FOUND THEN
      BEGIN
        INSERT INTO public.auth_login_attempt_throttle (
          bucket_type,
          username_hash,
          ip_address,
          failed_count,
          window_started_at,
          last_failed_at,
          blocked_until,
          updated_at
        )
        VALUES (
          p_bucket_type,
          p_username_hash,
          p_ip_address,
          1,
          v_now,
          v_now,
          CASE WHEN p_threshold <= 1 THEN v_now + p_block_duration ELSE NULL END,
          v_now
        );
        RETURN TRUE;
      EXCEPTION WHEN unique_violation THEN
        NULL;
      END;
    ELSE
      v_reset_window :=
        v_row.window_started_at <= v_now - p_window
        OR (v_row.blocked_until IS NOT NULL AND v_row.blocked_until <= v_now);
      v_failed_count := CASE WHEN v_reset_window THEN 1 ELSE v_row.failed_count + 1 END;

      UPDATE public.auth_login_attempt_throttle
      SET failed_count = v_failed_count,
          window_started_at = CASE WHEN v_reset_window THEN v_now ELSE window_started_at END,
          last_failed_at = v_now,
          blocked_until = CASE
            WHEN v_failed_count >= p_threshold THEN v_now + p_block_duration
            ELSE blocked_until
          END,
          updated_at = v_now
      WHERE id = v_row.id;

      RETURN TRUE;
    END IF;
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION public.auth_login_throttle_check(
  p_username text,
  p_ip_address inet
)
RETURNS TABLE (
  allowed boolean,
  blocked_until timestamptz,
  retry_after_seconds integer,
  blocked_scope text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_now timestamptz := now();
  v_username_hash text;
  v_block record;
BEGIN
  IF NULLIF(btrim(p_username), '') IS NULL OR p_ip_address IS NULL THEN
    RETURN QUERY SELECT TRUE, NULL::timestamptz, 0, NULL::text;
    RETURN;
  END IF;

  v_username_hash := public._auth_login_throttle_username_hash(p_username);

  SELECT bucket_type, blocked_until
  INTO v_block
  FROM public.auth_login_attempt_throttle
  WHERE ip_address = p_ip_address
    AND blocked_until > v_now
    AND (
      (bucket_type = 'username_ip' AND username_hash = v_username_hash)
      OR (bucket_type = 'ip' AND username_hash IS NULL)
    )
  ORDER BY blocked_until DESC
  LIMIT 1;

  IF FOUND THEN
    RETURN QUERY SELECT
      FALSE,
      v_block.blocked_until,
      GREATEST(1, CEIL(EXTRACT(EPOCH FROM (v_block.blocked_until - v_now)))::integer),
      v_block.bucket_type;
    RETURN;
  END IF;

  RETURN QUERY SELECT TRUE, NULL::timestamptz, 0, NULL::text;
END;
$$;

CREATE OR REPLACE FUNCTION public.auth_login_throttle_record_failure(
  p_username text,
  p_ip_address inet
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_username_hash text;
BEGIN
  IF NULLIF(btrim(p_username), '') IS NULL OR p_ip_address IS NULL THEN
    RETURN TRUE;
  END IF;

  v_username_hash := public._auth_login_throttle_username_hash(p_username);

  PERFORM public._auth_login_throttle_record_bucket(
    'username_ip',
    v_username_hash,
    p_ip_address,
    5,
    interval '30 minutes',
    interval '30 minutes'
  );

  PERFORM public._auth_login_throttle_record_bucket(
    'ip',
    NULL,
    p_ip_address,
    20,
    interval '30 minutes',
    interval '30 minutes'
  );

  RETURN TRUE;
EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'auth_login_throttle_record_failure failed: %', SQLERRM;
  RETURN FALSE;
END;
$$;

CREATE OR REPLACE FUNCTION public.auth_login_throttle_record_success(
  p_username text,
  p_ip_address inet
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NULLIF(btrim(p_username), '') IS NULL OR p_ip_address IS NULL THEN
    RETURN TRUE;
  END IF;

  DELETE FROM public.auth_login_attempt_throttle
  WHERE bucket_type = 'username_ip'
    AND username_hash = public._auth_login_throttle_username_hash(p_username)
    AND ip_address = p_ip_address;

  RETURN TRUE;
EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'auth_login_throttle_record_success failed: %', SQLERRM;
  RETURN FALSE;
END;
$$;

CREATE OR REPLACE FUNCTION public.auth_login_throttle_cleanup()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_deleted_count integer;
BEGIN
  DELETE FROM public.auth_login_attempt_throttle
  WHERE updated_at < now() - interval '1 day'
    AND (blocked_until IS NULL OR blocked_until < now() - interval '30 minutes');

  GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
  RETURN v_deleted_count;
END;
$$;

ALTER TABLE public.auth_audit_log
  DROP CONSTRAINT IF EXISTS auth_audit_log_reason_code_check;

ALTER TABLE public.auth_audit_log
  ADD CONSTRAINT auth_audit_log_reason_code_check CHECK (
    reason_code IS NULL OR reason_code = ANY (ARRAY[
      'invalid_credentials',
      'rpc_error',
      'tenant_inactive',
      'authorize_exception',
      'config_error',
      'rate_limited'
    ]::text[])
  );

REVOKE ALL ON FUNCTION public._auth_login_throttle_username_hash(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public._auth_login_throttle_username_hash(text) FROM anon;
REVOKE ALL ON FUNCTION public._auth_login_throttle_username_hash(text) FROM authenticated;

REVOKE ALL ON FUNCTION public._auth_login_throttle_record_bucket(
  text, text, inet, integer, interval, interval
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public._auth_login_throttle_record_bucket(
  text, text, inet, integer, interval, interval
) FROM anon;
REVOKE ALL ON FUNCTION public._auth_login_throttle_record_bucket(
  text, text, inet, integer, interval, interval
) FROM authenticated;

REVOKE ALL ON FUNCTION public.auth_login_throttle_check(text, inet) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.auth_login_throttle_check(text, inet) FROM anon;
REVOKE ALL ON FUNCTION public.auth_login_throttle_check(text, inet) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.auth_login_throttle_check(text, inet) TO service_role;

REVOKE ALL ON FUNCTION public.auth_login_throttle_record_failure(text, inet) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.auth_login_throttle_record_failure(text, inet) FROM anon;
REVOKE ALL ON FUNCTION public.auth_login_throttle_record_failure(text, inet) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.auth_login_throttle_record_failure(text, inet) TO service_role;

REVOKE ALL ON FUNCTION public.auth_login_throttle_record_success(text, inet) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.auth_login_throttle_record_success(text, inet) FROM anon;
REVOKE ALL ON FUNCTION public.auth_login_throttle_record_success(text, inet) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.auth_login_throttle_record_success(text, inet) TO service_role;

REVOKE ALL ON FUNCTION public.auth_login_throttle_cleanup() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.auth_login_throttle_cleanup() FROM anon;
REVOKE ALL ON FUNCTION public.auth_login_throttle_cleanup() FROM authenticated;
GRANT EXECUTE ON FUNCTION public.auth_login_throttle_cleanup() TO service_role;

COMMENT ON TABLE public.auth_login_attempt_throttle IS
'Bounded login-attempt throttle state for credentials auth. Audit history remains in auth_audit_log.';

COMMENT ON FUNCTION public.auth_login_throttle_check(text, inet) IS
'Service-role-only check for credentials login throttling. Returns allowed=false when username+IP or IP-only bucket is temporarily blocked.';

COMMENT ON FUNCTION public.auth_login_throttle_record_failure(text, inet) IS
'Service-role-only recorder for failed credentials attempts. Blocks username+IP after 5 failures and IP-only after 20 failures in 30 minutes.';

COMMENT ON FUNCTION public.auth_login_throttle_record_success(text, inet) IS
'Service-role-only reset for successful credentials login. Resets username+IP bucket only.';

NOTIFY pgrst, 'reload schema';

COMMIT;
