-- Issue #366 / #378 Batch 3: persistent auth audit sink.
-- Scope:
--   - create append-only public.auth_audit_log
--   - add service-role-only public.auth_audit_log_insert(...)
--   - add forensic indexes for auth investigations
--
-- Out of scope:
--   - applying this migration in the current implementation session
--   - adding read RPCs for auth audit forensics
--   - retention / cleanup policy
--
-- Rollback:
--   DROP FUNCTION IF EXISTS public.auth_audit_log_insert(
--     timestamptz, text, text, text, text, text, text, text, text, text, inet, text, jsonb
--   );
--   DROP TABLE IF EXISTS public.auth_audit_log;

BEGIN;

CREATE TABLE IF NOT EXISTS public.auth_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  event text NOT NULL,
  reason_code text NULL,
  signout_reason text NULL,
  user_id text NULL,
  username text NULL,
  tenant_id text NULL,
  request_id text NULL,
  trace_id text NULL,
  source text NOT NULL,
  ip_address inet NULL,
  user_agent text NULL,
  metadata jsonb NULL,
  CONSTRAINT auth_audit_log_event_check CHECK (
    event = ANY (ARRAY[
      'login_success',
      'login_failure',
      'tenant_inactive',
      'profile_refresh_failed',
      'token_invalidated_password_change',
      'signout',
      'forced_signout'
    ]::text[])
  ),
  CONSTRAINT auth_audit_log_source_check CHECK (
    source = ANY (ARRAY[
      'authorize',
      'jwt_callback',
      'events_signin',
      'events_signout'
    ]::text[])
  ),
  CONSTRAINT auth_audit_log_reason_code_check CHECK (
    reason_code IS NULL OR reason_code = ANY (ARRAY[
      'invalid_credentials',
      'rpc_error',
      'tenant_inactive',
      'authorize_exception',
      'config_error'
    ]::text[])
  ),
  CONSTRAINT auth_audit_log_signout_reason_check CHECK (
    signout_reason IS NULL OR signout_reason = ANY (ARRAY[
      'user_initiated',
      'session_expired',
      'forced_password_change'
    ]::text[])
  )
);

CREATE INDEX IF NOT EXISTS idx_auth_audit_log_created_at_brin
  ON public.auth_audit_log
  USING brin (created_at);

CREATE INDEX IF NOT EXISTS idx_auth_audit_log_user_created_at
  ON public.auth_audit_log
  USING btree (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_auth_audit_log_event_created_at
  ON public.auth_audit_log
  USING btree (event, created_at DESC);

REVOKE ALL ON TABLE public.auth_audit_log FROM PUBLIC;
REVOKE ALL ON TABLE public.auth_audit_log FROM anon;
REVOKE ALL ON TABLE public.auth_audit_log FROM authenticated;

CREATE OR REPLACE FUNCTION public.auth_audit_log_insert(
  p_created_at timestamptz DEFAULT now(),
  p_event text DEFAULT NULL,
  p_source text DEFAULT NULL,
  p_reason_code text DEFAULT NULL,
  p_signout_reason text DEFAULT NULL,
  p_user_id text DEFAULT NULL,
  p_username text DEFAULT NULL,
  p_tenant_id text DEFAULT NULL,
  p_request_id text DEFAULT NULL,
  p_trace_id text DEFAULT NULL,
  p_ip_address inet DEFAULT NULL,
  p_user_agent text DEFAULT NULL,
  p_metadata jsonb DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  BEGIN
    INSERT INTO public.auth_audit_log (
      created_at,
      event,
      reason_code,
      signout_reason,
      user_id,
      username,
      tenant_id,
      request_id,
      trace_id,
      source,
      ip_address,
      user_agent,
      metadata
    )
    VALUES (
      COALESCE(p_created_at, now()),
      p_event,
      p_reason_code,
      p_signout_reason,
      NULLIF(BTRIM(p_user_id), ''),
      NULLIF(BTRIM(p_username), ''),
      NULLIF(BTRIM(p_tenant_id), ''),
      NULLIF(BTRIM(p_request_id), ''),
      NULLIF(BTRIM(p_trace_id), ''),
      p_source,
      p_ip_address,
      NULLIF(BTRIM(p_user_agent), ''),
      p_metadata
    );

    RETURN TRUE;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'auth_audit_log_insert failed: %', SQLERRM;
    RETURN FALSE;
  END;
END;
$$;

REVOKE ALL ON FUNCTION public.auth_audit_log_insert(
  timestamptz, text, text, text, text, text, text, text, text, text, inet, text, jsonb
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.auth_audit_log_insert(
  timestamptz, text, text, text, text, text, text, text, text, text, inet, text, jsonb
) FROM anon;
REVOKE ALL ON FUNCTION public.auth_audit_log_insert(
  timestamptz, text, text, text, text, text, text, text, text, text, inet, text, jsonb
) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.auth_audit_log_insert(
  timestamptz, text, text, text, text, text, text, text, text, text, inet, text, jsonb
) TO service_role;

COMMENT ON FUNCTION public.auth_audit_log_insert(
  timestamptz, text, text, text, text, text, text, text, text, text, inet, text, jsonb
) IS
'Service-role-only auth lifecycle audit sink for NextAuth server callbacks. Returns FALSE on insert failure so auth behavior never depends on persistence.';

COMMENT ON TABLE public.auth_audit_log IS
'Append-only auth lifecycle audit sink for Issue #378. Read-side access is intentionally deferred to a follow-up issue.';

NOTIFY pgrst, 'reload schema';

COMMIT;
