-- Issue #527: side-by-side 768-dimensional category embeddings for DQSS rerank validation.
-- Keep public.nhom_thiet_bi.embedding vector(384) untouched for the existing rollout path.

BEGIN;

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.device_quota_category_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL REFERENCES public.nhom_thiet_bi(id) ON DELETE CASCADE,
  model_name TEXT NOT NULL,
  dimension INTEGER NOT NULL CHECK (dimension = 768),
  content_hash TEXT NOT NULL,
  embedding extensions.vector(768) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (category_id, model_name, dimension, content_hash)
);

CREATE INDEX IF NOT EXISTS device_quota_category_embeddings_lookup_idx
  ON public.device_quota_category_embeddings (category_id, model_name, dimension, updated_at DESC);

CREATE INDEX IF NOT EXISTS device_quota_category_embeddings_model_hash_idx
  ON public.device_quota_category_embeddings (model_name, dimension, content_hash);

CREATE OR REPLACE FUNCTION public.touch_device_quota_category_embeddings_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_device_quota_category_embeddings_updated_at
  ON public.device_quota_category_embeddings;
CREATE TRIGGER trg_device_quota_category_embeddings_updated_at
BEFORE UPDATE ON public.device_quota_category_embeddings
FOR EACH ROW
EXECUTE FUNCTION public.touch_device_quota_category_embeddings_updated_at();

ALTER TABLE public.device_quota_category_embeddings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS device_quota_category_embeddings_no_client_access
  ON public.device_quota_category_embeddings;
CREATE POLICY device_quota_category_embeddings_no_client_access
  ON public.device_quota_category_embeddings
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

REVOKE ALL ON public.device_quota_category_embeddings FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.device_quota_category_embeddings TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.device_quota_category_embeddings_id_seq
  TO service_role;
REVOKE ALL ON FUNCTION public.touch_device_quota_category_embeddings_updated_at()
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.touch_device_quota_category_embeddings_updated_at()
  TO service_role;

COMMENT ON TABLE public.device_quota_category_embeddings IS
  'Server-only side-by-side 768-dimensional Device Quota category embeddings for DQSS validation. Existing nhom_thiet_bi.embedding vector(384) remains unchanged.';

COMMENT ON COLUMN public.device_quota_category_embeddings.content_hash IS
  'SHA-256 hash of the category text payload used to generate this embedding.';

COMMIT;
